### ISSUE TITLE
Update section 'Theory' in experiment 'Tchebichev Straight Line Mechanism'

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-mechanics-of-machine-lab-nitk#1]
Update section 'Theory' in experiment 'Tchebichev Straight Line Mechanism'

**Comment by sravanthimodepu** [comment]
Added the proper content in the Theory section of Tchebichev Straight Line Mechanism experiment.

**Comment by sravanthimodepu** [comment]
Arranged all the sections in proper order as "Theory, Procedure, Simulator, Assignment, Self-evaluation, Quiz, Video, Reference, Feedback" for all the experiments.

**Comment by sravanthimodepu** [comment]
Closing the issue.
